/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as ProductivityRouteImport } from "./routes/productivity"
import { Route as AppRouteImport } from "./routes/app"
import { Route as AuthRouteImport } from "./routes/_auth"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as AppProjectsRouteImport } from "./routes/app/projects"
import { Route as AppBillingRouteImport } from "./routes/app/billing"
import { Route as AppAssetsRouteImport } from "./routes/app/assets"
import { Route as AuthSignupRouteImport } from "./routes/_auth/signup"
import { Route as AuthLoginRouteImport } from "./routes/_auth/login"

const ProductivityRoute = ProductivityRouteImport.update({
  id: "/productivity",
  path: "/productivity",
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: "/app",
  path: "/app",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: "/projects",
  path: "/projects",
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: "/billing",
  path: "/billing",
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsRoute = AppAssetsRouteImport.update({
  id: "/assets",
  path: "/assets",
  getParentRoute: () => AppRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/app": typeof AppRouteWithChildren
  "/productivity": typeof ProductivityRoute
  "/login": typeof AuthLoginRoute
  "/signup": typeof AuthSignupRoute
  "/app/assets": typeof AppAssetsRoute
  "/app/billing": typeof AppBillingRoute
  "/app/projects": typeof AppProjectsRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/app": typeof AppRouteWithChildren
  "/productivity": typeof ProductivityRoute
  "/login": typeof AuthLoginRoute
  "/signup": typeof AuthSignupRoute
  "/app/assets": typeof AppAssetsRoute
  "/app/billing": typeof AppBillingRoute
  "/app/projects": typeof AppProjectsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/_auth": typeof AuthRouteWithChildren
  "/app": typeof AppRouteWithChildren
  "/productivity": typeof ProductivityRoute
  "/_auth/login": typeof AuthLoginRoute
  "/_auth/signup": typeof AuthSignupRoute
  "/app/assets": typeof AppAssetsRoute
  "/app/billing": typeof AppBillingRoute
  "/app/projects": typeof AppProjectsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/app"
    | "/productivity"
    | "/login"
    | "/signup"
    | "/app/assets"
    | "/app/billing"
    | "/app/projects"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/app"
    | "/productivity"
    | "/login"
    | "/signup"
    | "/app/assets"
    | "/app/billing"
    | "/app/projects"
  id:
    | "__root__"
    | "/"
    | "/_auth"
    | "/app"
    | "/productivity"
    | "/_auth/login"
    | "/_auth/signup"
    | "/app/assets"
    | "/app/billing"
    | "/app/projects"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  ProductivityRoute: typeof ProductivityRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/productivity": {
      id: "/productivity"
      path: "/productivity"
      fullPath: "/productivity"
      preLoaderRoute: typeof ProductivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/app": {
      id: "/app"
      path: "/app"
      fullPath: "/app"
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_auth": {
      id: "/_auth"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/app/projects": {
      id: "/app/projects"
      path: "/projects"
      fullPath: "/app/projects"
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    "/app/billing": {
      id: "/app/billing"
      path: "/billing"
      fullPath: "/app/billing"
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    "/app/assets": {
      id: "/app/assets"
      path: "/assets"
      fullPath: "/app/assets"
      preLoaderRoute: typeof AppAssetsRouteImport
      parentRoute: typeof AppRoute
    }
    "/_auth/signup": {
      id: "/_auth/signup"
      path: "/signup"
      fullPath: "/signup"
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/login": {
      id: "/_auth/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AppRouteChildren {
  AppAssetsRoute: typeof AppAssetsRoute
  AppBillingRoute: typeof AppBillingRoute
  AppProjectsRoute: typeof AppProjectsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssetsRoute: AppAssetsRoute,
  AppBillingRoute: AppBillingRoute,
  AppProjectsRoute: AppProjectsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  ProductivityRoute: ProductivityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from "./router.tsx"
import type { startInstance } from "./start.tsx"
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
