// Cloudflare Workers environment bindings
// This file is generated by wrangler types command
// Run: wrangler types packages/env/src/cloudflare.d.ts --env-interface Env

// Placeholder interface for typecheck when wrangler types hasn't been run
// This will be replaced by wrangler types command
export interface Env {
  DATABASE: { connectionString: string };
  BUCKET: R2Bucket;
  AI: any;
  [key: string]: unknown;
}
